/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


import java.util.List;

class AppTest {
   @Test
  

   void testTask1(){
    List<Integer> a = List.of(7, 42, 19, 3, 88, 21, 56, 14, 67, 30);

    List<Integer> b = List.of(3, 12, 7, 3, 45, 8, 19, 2, 27, 3);

    assertEquals(109,SimpleFunctions.Task1(a, b), "failed should be 109");


   }
   // Test case for Task6 by Monde Quluba g23q5609
   @Test 
   public void test_RoundUpToNearest100(){
      SimpleFunctions mq = new SimpleFunctions();
      List<Integer> input = Arrays.asList(45, 150, 299, 100);
      List<Integer> expected = Arrays.asList(100, 200, 300, 100);

      assertEquals(expected, mq.listRoundUp(input));
   }

}